name: Auto Fix

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  auto-fix:
    name: Auto Fix Code Issues
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[auto-fix]')"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Check for formatting issues
      id: check
      run: |
        echo "checking=true" >> $GITHUB_OUTPUT
        ./gradlew spotlessCheck || echo "needs_fix=true" >> $GITHUB_OUTPUT
        
    - name: Apply automatic fixes
      if: steps.check.outputs.needs_fix == 'true'
      run: |
        echo "Applying Spotless formatting fixes..."
        ./gradlew spotlessApply
        
    - name: Check for Ktlint issues and fix
      if: steps.check.outputs.needs_fix == 'true'
      run: |
        echo "Checking and fixing Ktlint issues..."
        ./gradlew ktlintFormat || true
        
    - name: Verify fixes
      if: steps.check.outputs.needs_fix == 'true'
      run: |
        ./gradlew spotlessCheck
        ./gradlew ktlintCheck
        
    - name: Commit and push fixes
      if: steps.check.outputs.needs_fix == 'true'
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: |
          🤖 Auto-fix: Apply code formatting and linting fixes [auto-fix] [skip ci]
          
          - Applied Spotless formatting
          - Fixed Ktlint violations
          
          Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
        branch: ${{ github.head_ref || github.ref_name }}
        commit_user_name: github-actions[bot]
        commit_user_email: github-actions[bot]@users.noreply.github.com